### ISSUE TITLE
Wrong

### ISSUE THREAD

**Issue by WhiskyModz** [chr1srbx/Critical-Ops-Mod-Menu#1]
Memcheck bypass failed entity list is wrong also old versions of your project will work better now not suitable for use Failure lol

**Comment by chr1srbx** [comment]
Check the date, I had less knowledge back then, Memcheck might not work because its old.

**Comment by WhiskyModz** [comment]
critical ops changed. Many things don't work anymore. Bypass signature always gives me a ban. I'm using an executable

**Comment by chr1srbx** [comment]
Find a new method then.

**Comment by WhiskyModz** [comment]
Using rooted cheats is the only solution

**Comment by WhiskyModz** [comment]
You create a new modmenu source if you need help contact me. I've been making mods for this game for 3 years

**Comment by chr1srbx** [comment]
Discord?

**Comment by WhiskyModz** [comment]
WhiskyBack?#6161
